<?php

return [
    'MIDTRANS_SERVER_KEY' => $_ENV['MIDTRANS_SERVER_KEY'],
    'MIDTRANS_IS_PRODUCTION' => $_ENV['MIDTRANS_IS_PRODUCTION'],
    'MIDTRANS_IS_SANITIZED' => $_ENV['MIDTRANS_IS_SANITIZED'],
    'MIDTRANS_IS_3DS' => $_ENV['MIDTRANS_IS_3DS']
];